let a=20;
let b=40;
console.log('a+b=' ,a+b)
console.log('a-b=' ,a-b)
console.log('a*b=' ,a*b)
console.log('a/b=' ,a/b)
console.log('a++=' ,a++)
console.log('++a=',++a) 
console.log('a-- =',a--)
console.log('--a =',--a)
console.log('a =',a)
console.log('a-- =',a--)